apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: grafana
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: agent-secret
    template:
      engineVersion: v2
      data:
        token: '{{ printf "{{ index . %s }}" .Values.clusterName }}'
  dataFrom:
    - extract:
        key: gitlab-agent-tokens
